name: Build Executables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        
    - name: Build executable (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        nuitka \
          --standalone \
          --output-filename=anitrack \
          --output-dir=dist \
          --include-data-file=styles.tcss=styles.tcss \
          --assume-yes-for-downloads \
          --remove-output \
          main.py
          
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        nuitka --standalone --output-filename=anitrack.exe --output-dir=dist --include-data-file=styles.tcss=styles.tcss --assume-yes-for-downloads --remove-output main.py
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: anitrack-${{ matrix.os }}
        path: dist/
