name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.9)'
        required: true
        default: 'v0.1.9'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            ## Python TUI Installation Instructions

            1. Install `uv` (https://docs.astral.sh/uv/getting-started/installation/)
            2. Install [mpv](github.com/mpv-player/mpv) player.
            3. (Optional) On desktop, set up **Anime4K** anime upscaler for **mpv**: https://github.com/bloc97/anime4k
            4. Run `uv tool install frixa-anitrack`
            5. Run `anitrack`

            NOTE: to try without installing, run `uv tool run --from frixa-anitrack anitrack` or `uvx --from frixa-anitrack anitrack`
          draft: false
          prerelease: false
